version: "3.2"
services:
  volumes:
    pgdata:
        driver: local

services:
   pg_db:
      restart: unless-stopped
      container_name: pg_db
      image: postgres
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: '123456'
         POSTGRES_DB: netdb
         PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
         - ./pgdata/:/var/lib/postgresql/data/pgdata
      ports:
         - 5432:5432

   server:
      restart: unless-stopped
      build:
         context: .
         dockerfile: dockerfile-api
      ports:
         - 8000:8000
      command: "bash entrypoint.sh"
      env_file:
         - env.conf
      links:
         - client

   client:
      restart: unless-stopped
      build:
         context: .
         dockerfile: dockerfile-client
      ports:
         - 3000:3000
      command: server.js
      links:
         - pg_db

   nginx:
      restart: unless-stopped
      image: nginx
      expose:
         - 8080
      ports:
         - 8080:8080
      volumes:
         - ./net/static/:/srv/www/net/static/
         - ./net/logs:/srv/www/net/logs
         - ./nginx-server.conf:/etc/nginx/conf.d/default.conf
      links:
         - server
