FROM node:14-alpine

COPY ./front-server /srv/www/net/front-server/
COPY ./front /srv/www/net/front/
WORKDIR /srv/www/net/front/

RUN yarn install
RUN yarn run build
RUN cp -r /srv/www/net/front/dist/ /srv/www/net/front-server/staticfiles

WORKDIR /srv/www/net/front-server/

RUN yarn install