# Generated by Django 3.1.1 on 2020-12-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptime',
            name='a_time',
            field=models.CharField(choices=[('11:00', '11:00'), ('20:30', '20:30'), ('17:30', '17:30'), ('12:30', '12:30'), ('14:30', '14:30'), ('16:00', '16:00'), ('13:30', '13:30'), ('18:30', '18:30'), ('15:30', '15:30'), ('12:00', '12:00'), ('10:30', '10:30'), ('20:00', '20:00'), ('11:30', '11:30'), ('15:00', '15:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:30', '19:30'), ('16:30', '16:30'), ('13:00', '13:00'), ('10:00', '10:00'), ('14:00', '14:00'), ('19:00', '19:00')], max_length=10, verbose_name='Доступное время'),
        ),
    ]
