# Generated by Django 3.1.1 on 2020-12-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netWeb', '0002_auto_20201215_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signuptime',
            options={'ordering': ['a_time'], 'verbose_name': 'Доступные интервалы', 'verbose_name_plural': 'Доступные интервалы'},
        ),
        migrations.AlterField(
            model_name='signuptime',
            name='a_time',
            field=models.CharField(choices=[(6, '12:30'), (4, '11:30'), (15, '17:00'), (17, '18:00'), (19, '19:00'), (18, '18:30'), (8, '13:30'), (22, '20:30'), (14, '16:30'), (20, '19:30'), (1, '10:00'), (11, '15:00'), (16, '17:30'), (12, '15:30'), (5, '12:00'), (9, '14:00'), (7, '13:00'), (21, '20:00'), (10, '14:30'), (13, '16:00'), (3, '11:00'), (2, '10:30')], max_length=10, verbose_name='Доступное время'),
        ),
    ]
